# Generated by Django 5.0 on 2024-01-02 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='confrom_password',
            new_name='confirm_password',
        ),
    ]
